runtime: python39

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /(.+\.(webmanifest))
  static_files: webapp/manifest.webmanifest
  upload: webapp/manifest.webmanifest
  mime_type: application/manifest+json
  expiration: "0s"

- url: /(.+\.(webapp))
  static_files: webapp/manifest.webapp
  upload: webapp/manifest.webapp
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"

- url: /alerts
  script: auto

- url: /scrape
  script: auto

- url: /delays
  script: auto

- url: /(.+)
  static_files: webapp/\1
  upload: webapp/(.+)
