runtime: python27
api_version: 1
threadsafe: true

skip_files:
- .git/
- downloads/
- node_modules/

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /(.+)
  static_files: webapp/\1
  upload: webapp/(.+)

# Manifest files

- url: /(.+\.(appcache))
  static_files: \1
  upload: static/(.+\.(appcache))
  mime_type: text/cache-manifest
  expiration: "0s"

- url: /(.+\.(webapp))
  static_files: \1
  upload: (.+\.(webapp))
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"
