runtime: python27
api_version: 1
threadsafe: true

skip_files:
- .git/
- downloads/
- node_modules/

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /(.+)
  static_files: webapp/\1
  upload: webapp/(.+)
