runtime: ruby30
entrypoint: bundle exec ruby app.rb

#     Memory  CPU      Instance hour
# F1  128 MB  600 MHz  $0.05 - $0.07 default
# F2  256 MB  1.2 GHz  $0.10 - $0.13
# F4  512 MB  2.4 GHz  $0.20 - $0.26
# instance_class: F2

skip_files:
- .git/
- downloads/
- node_modules/

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /(.+\.(webapp))
  static_files: webapp/manifest.webapp
  upload: webapp/manifest.webapp
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"

- url: /status
  script: auto

- url: /scrape
  script: auto

- url: /(.+)
  static_files: webapp/\1
  upload: webapp/(.+)
