runtime: python27
api_version: 1
threadsafe: true

skip_files:
- .git/
- downloads/
- node_modules/

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /(.+)
  static_files: webapp/\1
  upload: webapp/(.+)

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"
