runtime: ruby30
entrypoint: bundle exec ruby app.rb

skip_files:
- .git/
- downloads/
- node_modules/

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/index.html

- url: /(.+\.(webapp))
  static_files: webapp/manifest.webapp
  upload: webapp/manifest.webapp
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"

- url: /status
  script: auto

- url: /scrape
  script: auto

- url: /(.+)
  static_files: webapp/\1
  upload: webapp/(.+)
