name: Comment when issue moves columns

on:
  project_card:
    types: [moved]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: logging
        run: echo "assigned" # "moved columns in project"
