name: Comment when issue moves columns

on:
  issues:
    types: [moved_columns_in_project]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: logging
        run: echo "moved columns in project"
